#!/bin/vbash

# Guest Zone - Guest VLAN
set firewall zone zn_guest default-action 'drop'
set firewall zone zn_guest description 'Guest Zone - Guest VLAN'
set firewall zone zn_guest from zn_iot firewall name 'iot-to-guest'
set firewall zone zn_guest from zn_trusted firewall name 'trusted-to-guest'
set firewall zone zn_guest from zn_untrusted firewall name 'untrusted-to-guest'
set firewall zone zn_guest from zn_local firewall name 'local-to-guest'
set firewall zone zn_guest from zn_containers firewall name 'containers-to-guest'
set firewall zone zn_guest from zn_wan firewall name 'wan-to-guest'
set firewall zone zn_guest interface 'eth5.50'

# IoT Zone - IoT VLAN
set firewall zone zn_iot default-action 'drop'
set firewall zone zn_iot description 'IoT Zone - IoT VLAN'
set firewall zone zn_iot from zn_guest firewall name 'guest-to-iot'
set firewall zone zn_iot from zn_trusted firewall name 'trusted-to-iot'
set firewall zone zn_iot from zn_untrusted firewall name 'untrusted-to-iot'
set firewall zone zn_iot from zn_local firewall name 'local-to-iot'
set firewall zone zn_iot from zn_containers firewall name 'containers-to-iot'
set firewall zone zn_iot from zn_wan firewall name 'wan-to-iot'
set firewall zone zn_iot interface 'eth5.100'

# Trusted Zone - LAN / Servers / Corosync / Management / Cluster-1 / Cluster-2 / Ceph / VPN / Inter-VLAN / Wireguard
set firewall zone zn_trusted default-action 'drop'
set firewall zone zn_trusted description 'Trusted Zone - LAN / Servers / Corosync / Management / Cluster-1 / Cluster-2 / Ceph / VPN / Inter-VLAN / Wireguard'
set firewall zone zn_trusted from zn_guest firewall name 'guest-to-trusted'
set firewall zone zn_trusted from zn_iot firewall name 'iot-to-trusted'
set firewall zone zn_trusted from zn_untrusted firewall name 'untrusted-to-trusted'
set firewall zone zn_trusted from zn_local firewall name 'local-to-trusted'
set firewall zone zn_trusted from zn_containers firewall name 'containers-to-trusted'
set firewall zone zn_trusted from zn_wan firewall name 'wan-to-trusted'
set firewall zone zn_trusted interface 'eth5.2' 
set firewall zone zn_trusted interface 'eth5.200'       
set firewall zone zn_trusted interface 'eth5.1999'
set firewall zone zn_trusted interface 'eth5.2000'
set firewall zone zn_trusted interface 'eth5.2001'
set firewall zone zn_trusted interface 'eth5.2002'
set firewall zone zn_trusted interface 'eth5.2040'
set firewall zone zn_trusted interface 'eth5.2300'
set firewall zone zn_trusted interface 'eth5.4040'
set firewall zone zn_trusted interface 'wg2'

# Untrusted Zone - Untrusted VLAN
set firewall zone zn_untrusted default-action 'drop'
set firewall zone zn_untrusted description 'Untrusted Zone - Untrusted VLAN'
set firewall zone zn_untrusted from zn_guest firewall name 'guest-to-untrusted'
set firewall zone zn_untrusted from zn_iot firewall name 'iot-to-untrusted'
set firewall zone zn_untrusted from zn_trusted firewall name 'trusted-to-untrusted'
set firewall zone zn_untrusted from zn_local firewall name 'local-to-untrusted'
set firewall zone zn_untrusted from zn_containers firewall name 'containers-to-untrusted'
set firewall zone zn_untrusted from zn_wan firewall name 'wan-to-untrusted'
set firewall zone zn_untrusted interface 'eth5.1'

# Local Zone - VyOS itself
set firewall zone zn_local default-action 'drop'
set firewall zone zn_local description 'Local Zone - VyOS itself'
set firewall zone zn_local from zn_guest firewall name 'guest-to-local'
set firewall zone zn_local from zn_iot firewall name 'iot-to-local'
set firewall zone zn_local from zn_trusted firewall name 'trusted-to-local'
set firewall zone zn_local from zn_untrusted firewall name 'untrusted-to-local'
set firewall zone zn_local from zn_containers firewall name 'containers-to-local'
set firewall zone zn_local from zn_wan firewall name 'wan-to-local'
set firewall zone zn_local local-zone

# Container Zone - Podman on VyOS
set firewall zone zn_containers default-action 'drop'
set firewall zone zn_containers description 'Container Zone - Podman on VyOS'
set firewall zone zn_containers from zn_guest firewall name 'guest-to-containers'
set firewall zone zn_containers from zn_iot firewall name 'iot-to-containers'
set firewall zone zn_containers from zn_trusted firewall name 'trusted-to-containers'
set firewall zone zn_containers from zn_untrusted firewall name 'untrusted-to-containers'
set firewall zone zn_containers from zn_local firewall name 'local-to-containers'
set firewall zone zn_containers from zn_wan firewall name 'wan-to-containers'
set firewall zone zn_containers interface 'pod-containers'

# WAN Zone - Outside world
set firewall zone zn_wan from zn_guest firewall name 'guest-wan'
set firewall zone zn_wan description 'WAN Zone - Outside world'
set firewall zone zn_wan from zn_guest firewall name 'guest-to-wan'
set firewall zone zn_wan from zn_iot firewall name 'iot-to-wan'
set firewall zone zn_wan from zn_trusted firewall name 'trusted-to-wan'
set firewall zone zn_wan from zn_untrusted firewall name 'untrusted-to-wan'
set firewall zone zn_wan from zn_local firewall name 'local-to-wan'
set firewall zone zn_wan from zn_containers firewall name 'containers-to-wan'
set firewall zone zn_wan interface 'eth1'
